In [1]:
import pandas as pd
x= pd.read_csv("C:/Users/admin/Downloads/12.real state.csv")
x

,street,city,zip,state,beds,baths,sq__ft,type,sale_date,price,latitude,longitude
0,3526 HIGH ST,SACRAMENTO,95838,CA,2,1,836,Residential,Wed May 21 00:00:00 EDT 2008,59222,38.631913,-121.434879
1,51 OMAHA CT,SACRAMENTO,95823,CA,3,1,1167,Residential,Wed May 21 00:00:00 EDT 2008,68212,38.478902,-121.431028
2,2796 BRANCH ST,SACRAMENTO,95815,CA,2,1,796,Residential,Wed May 21 00:00:00 EDT 2008,68880,38.618305,-121.443839
3,2805 JANETTE WAY,SACRAMENTO,95815,CA,2,1,852,Residential,Wed May 21 00:00:00 EDT 2008,69307,38.616835,-121.439146
4,6001 MCMAHON DR,SACRAMENTO,95824,CA,2,1,797,Residential,Wed May 21 00:00:00 EDT 2008,81900,38.519470,-121.435768
...,...,...,...,...,...,...,...,...,...,...,...,...
980,9169 GARLINGTON CT,SACRAMENTO,95829,CA,4,3,2280,Residential,Thu May 15 00:00:00 EDT 2008,232425,38.457679,-121.359620
981,6932 RUSKUT WAY,SACRAMENTO,95823,CA,3,2,1477,Residential,Thu May 15 00:00:00 EDT 2008,234000,38.499893,-121.458890
982,7933 DAFFODIL WAY,CITRUS HEIGHTS,95610,CA,3,2,1216,Residential,Thu May 15 00:00:00 EDT 2008,235000,38.708824,-121.256803
983,8304 RED FOX WAY,ELK GROVE,95758,CA,4,2,1685,Residential,Thu May 15 00:00:00 EDT 2008,235301,38.417000,-121.397424
984,3882 YELLOWSTONE LN,EL DORADO HILLS,95762,CA,3,2,1362,Residential,Thu May 15 00:00:00 EDT 2008,235738,38.655245,-121.075915

In [3]:
x.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 985 entries, 0 to 984
Data columns (total 12 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   street     985 non-null    object
 1   city       985 non-null    object
 2   zip        985 non-null    int64
 3   state      985 non-null    object
 4   beds       985 non-null    int64
 5   baths      985 non-null    int64
 6   sq__ft     985 non-null    int64
 7   type       985 non-null    object
 8   sale_date  985 non-null    object
 9   price      985 non-null    int64
 10  latitude   985 non-null    float64
 11  longitude  985 non-null    float64
dtypes: float64(2), int64(5), object(5)
memory usage: 92.5+ KB

In [27]:
#city wise list of villa which is less than 10000
city = x[(x['type'] == 'villa') & (x['price']>=10000)]
print(city[['street', 'city', 'zip', 'state', 'beds', 'baths', 'sq__ft', 'type',
            'sale_date', 'price', 'latitude', 'longitude']])
print= x.head(5)

                                  street            city    zip state  beds  \
5                     5828 PEPPERMILL CT      SACRAMENTO  95841    CA     3
8        11150 TRINITY RIVER DR Unit 114  RANCHO CORDOVA  95670    CA     2
15                        7340 HAMDEN PL      SACRAMENTO  95842    CA     2
17               6236 LONGFORD DR Unit 1  CITRUS HEIGHTS  95621    CA     2
30          5201 LAGUNA OAKS DR Unit 140       ELK GROVE  95758    CA     2
34          5201 LAGUNA OAKS DR Unit 162       ELK GROVE  95758    CA     2
39                      2442 LARKSPUR LN      SACRAMENTO  95825    CA     1
40          4800 WESTLAKE PKWY Unit 2109      SACRAMENTO  95835    CA     2
94                          4010 ALEX LN      CARMICHAEL  95608    CA     2
101              4236 NATOMAS CENTRAL DR      SACRAMENTO  95834    CA     3
158              6272 LONGFORD DR Unit 1  CITRUS HEIGHTS  95621    CA     2
160          9512 EMERALD PARK DR Unit 3       ELK GROVE  95624    CA     2
171         5201 LAGUNA OAKS DR Unit 199       ELK GROVE  95758    CA     1
173         5201 LAGUNA OAKS DR Unit 172       ELK GROVE  95758    CA     1
190            5333 PRIMROSE DR Unit 19A       FAIR OAKS  95628    CA     2
192         5201 LAGUNA OAKS DR Unit 126       ELK GROVE  95758    CA     0
236                      2340 HURLEY WAY      SACRAMENTO  95825    CA     0
248                  611 BLOSSOM ROCK LN          FOLSOM  95630    CA     0
279     11281 STANFORD COURT LN Unit 604      GOLD RIVER  95670    CA     0
335                      5840 WALERGA RD      SACRAMENTO  95842    CA     2
336                       923 FULTON AVE      SACRAMENTO  95825    CA     1
343          5050 RHODE ISLAND DR Unit 4      SACRAMENTO  95841    CA     2
344                   4513 GREENHOLME DR      SACRAMENTO  95842    CA     2
349                      9058 MONTOYA ST      SACRAMENTO  95826    CA     2
354          3715 TALLYHO DR Unit 78HIGH      SACRAMENTO  95826    CA     1
362                      8020 WALERGA RD        ANTELOPE  95843    CA     2
363                    167 VALLEY OAK DR       ROSEVILLE  95678    CA     2
368           4200 COMMERCE WAY Unit 711      SACRAMENTO  95834    CA     2
377                       9013 CASALS ST      SACRAMENTO  95826    CA     2
378                  227 MAHAN CT Unit 1       ROSEVILLE  95678    CA     2
383                  7032 FAIR OAKS BLVD      CARMICHAEL  95608    CA     3
390  10001 WOODCREEK OAKS BLVD Unit 1415       ROSEVILLE  95747    CA     2
414               7110 STELLA LN Unit 15      CARMICHAEL  95608    CA     2
443                 4709 AMBER LN Unit 1      SACRAMENTO  95841    CA     2
446                      301 OLIVADI WAY      SACRAMENTO  95834    CA     2
453               3301 PARK DR Unit 1914      SACRAMENTO  95835    CA     3
468                2231 COUNTRY VILLA CT          AUBURN  95603    CA     2
511                     1322 SUTTER WALK      SACRAMENTO  95816    CA     0
613                     8248 CENTER PKWY      SACRAMENTO  95823    CA     2
617                    6063 LAND PARK DR      SACRAMENTO  95822    CA     2
622          4800 WESTLAKE PKWY Unit 410      SACRAMENTO  95835    CA     1
703                     1900 DANBROOK DR      SACRAMENTO  95835    CA     1
704                         140 VENTO CT       ROSEVILLE  95678    CA     3
814                      281 SPYGLASS HL       ROSEVILLE  95678    CA     3
868              9127 NEWHALL DR Unit 34      SACRAMENTO  95826    CA     1
870                  5672 HILLSDALE BLVD      SACRAMENTO  95842    CA     2
875                    550 DEL VERDE CIR      SACRAMENTO  95833    CA     2
881             739 E WOODSIDE LN Unit E      SACRAMENTO  95825    CA     1
888               3035 ESTEPA DR Unit 5C    CAMERON PARK  95682    CA     0
901             1530 TOPANGA LN Unit 204         LINCOLN  95648    CA     0
908               5754 WALERGA RD Unit 4      SACRAMENTO  95842    CA     2
922   10001 WOODCREEK OAKS BLVD Unit 815       ROSEVILLE  95747    CA     2
934             1550 TOPANGA LN Unit 207         LINCOLN  95648    CA     0
966                     9197 CORTINA CIR       ROSEVILLE  95678    CA     3

     baths  sq__ft   type                     sale_date   price   latitude  \
5        1    1122  villa  Wed May 21 00:00:00 EDT 2008   89921  38.662595
8        2     941  villa  Wed May 21 00:00:00 EDT 2008   94905  38.621188
15       2    1134  villa  Wed May 21 00:00:00 EDT 2008  110700  38.700051
17       1     795  villa  Wed May 21 00:00:00 EDT 2008  116250  38.679776
30       2    1039  villa  Wed May 21 00:00:00 EDT 2008  133000  38.423251
34       2    1039  villa  Wed May 21 00:00:00 EDT 2008  141000  38.423251
39       1     760  villa  Wed May 21 00:00:00 EDT 2008  150000  38.585140
40       2    1304  villa  Wed May 21 00:00:00 EDT 2008  152000  38.658812
94       2    1326  villa  Wed May 21 00:00:00 EDT 2008  250134  38.637028
101      2    1672  villa  Wed May 21 00:00:00 EDT 2008  265000  38.648879
158      1     795  villa  Tue May 20 00:00:00 EDT 2008   69000  38.680923
160      1     840  villa  Tue May 20 00:00:00 EDT 2008   71000  38.405730
171      1     722  villa  Tue May 20 00:00:00 EDT 2008   98000  38.423251
173      1     722  villa  Tue May 20 00:00:00 EDT 2008  100000  38.423251
190      2     994  villa  Tue May 20 00:00:00 EDT 2008  142500  38.662785
192      0       0  villa  Tue May 20 00:00:00 EDT 2008  145000  38.423251
236      0       0  villa  Tue May 20 00:00:00 EDT 2008  225000  38.588816
248      0       0  villa  Tue May 20 00:00:00 EDT 2008  240000  38.645700
279      0       0  villa  Tue May 20 00:00:00 EDT 2008  300000  38.625289
335      1     840  villa  Mon May 19 00:00:00 EDT 2008   40000  38.673678
336      1     484  villa  Mon May 19 00:00:00 EDT 2008   48000  38.582279
343      1     924  villa  Mon May 19 00:00:00 EDT 2008   77000  38.658739
344      1     795  villa  Mon May 19 00:00:00 EDT 2008   82732  38.669104
349      1     795  villa  Mon May 19 00:00:00 EDT 2008   90000  38.559144
354      1     625  villa  Mon May 19 00:00:00 EDT 2008  100000  38.544627
362      2     836  villa  Mon May 19 00:00:00 EDT 2008  115000  38.716070
363      2    1100  villa  Mon May 19 00:00:00 EDT 2008  115000  38.732429
368      2     958  villa  Mon May 19 00:00:00 EDT 2008  120000  38.647523
377      1     795  villa  Mon May 19 00:00:00 EDT 2008  126960  38.557045
378      1     780  villa  Mon May 19 00:00:00 EDT 2008  127000  38.749723
383      2    1245  villa  Mon May 19 00:00:00 EDT 2008  139500  38.628563
390      2       0  villa  Mon May 19 00:00:00 EDT 2008  150000  38.795529
414      2    1000  villa  Mon May 19 00:00:00 EDT 2008  182000  38.637396
443      1     756  villa  Mon May 19 00:00:00 EDT 2008  230522  38.657789
446      2    1250  villa  Mon May 19 00:00:00 EDT 2008  232500  38.644406
453      2    1678  villa  Mon May 19 00:00:00 EDT 2008  238000  38.665296
468      2    1255  villa  Mon May 19 00:00:00 EDT 2008  260000  38.931671
511      0       0  villa  Mon May 19 00:00:00 EDT 2008  360000  38.538050
613      1     906  villa  Fri May 16 00:00:00 EDT 2008   77000  38.459002
617      1     800  villa  Fri May 16 00:00:00 EDT 2008  104250  38.517029
622      1     846  villa  Fri May 16 00:00:00 EDT 2008  115000  38.658812
703      1     984  villa  Fri May 16 00:00:00 EDT 2008  210944  38.668433
704      2       0  villa  Fri May 16 00:00:00 EDT 2008  212500  38.793533
814      2    2100  villa  Fri May 16 00:00:00 EDT 2008  350000  38.762153
868      1     611  villa  Thu May 15 00:00:00 EDT 2008   60000  38.542419
870      1     933  villa  Thu May 15 00:00:00 EDT 2008   62000  38.670467
875      1     956  villa  Thu May 15 00:00:00 EDT 2008   92000  38.627147
881      1     682  villa  Thu May 15 00:00:00 EDT 2008  107666  38.578675
888      0       0  villa  Thu May 15 00:00:00 EDT 2008  119000  38.681393
901      0       0  villa  Thu May 15 00:00:00 EDT 2008  138000  38.884150
908      1     924  villa  Thu May 15 00:00:00 EDT 2008  150454  38.672567
922      2       0  villa  Thu May 15 00:00:00 EDT 2008  170000  38.795529
934      0       0  villa  Thu May 15 00:00:00 EDT 2008  188000  38.884170
966      2       0  villa  Thu May 15 00:00:00 EDT 2008  220000  38.793152

      longitude
5   -121.327813
8   -121.270555
15  -121.351278
17  -121.314089
30  -121.444489
34  -121.444489
39  -121.403736
40  -121.542345
94  -121.312963
101 -121.544023
158 -121.313945
160 -121.369832
171 -121.444489
173 -121.444489
190 -121.276272
192 -121.444489
236 -121.408549
248 -121.119700
279 -121.260286
335 -121.357471
336 -121.401482
343 -121.333561
344 -121.359008
349 -121.368387
354 -121.357960
362 -121.364468
363 -121.288069
368 -121.523217
377 -121.371670
378 -121.270080
383 -121.328297
390 -121.328819
414 -121.300055
443 -121.354994
446 -121.549049
453 -121.531993
468 -121.097862
511 -121.504700
613 -121.428794
617 -121.513809
622 -121.542345
703 -121.503471
704 -121.289685
814 -121.283451
868 -121.359904
870 -121.359799
875 -121.500799
881 -121.409951
888 -120.996713
901 -121.270277
908 -121.356754
922 -121.328819
934 -121.270222
966 -121.290025

In [6]:
#residentail type less than 800 sq__ft in city= 'Galt'
Galt_residential= x[(x['city']== 'GALT') & (x['type']== 'Residential') & (x['sq__ft'] > 800)]
print(Galt_residential[['street', 'sq__ft', 'sale_date', 'city']])

                  street  sq__ft                     sale_date  city
55    1122 WILD POPPY CT    1406  Wed May 21 00:00:00 EDT 2008  GALT
61      306 CAMELLIA WAY    1130  Wed May 21 00:00:00 EDT 2008  GALT
63            404 6TH ST    1479  Wed May 21 00:00:00 EDT 2008  GALT
174   1121 CREEKSIDE WAY    1080  Tue May 20 00:00:00 EDT 2008  GALT
189      840 TRANQUIL LN    1266  Tue May 20 00:00:00 EDT 2008  GALT
281        993 MANTON CT    2307  Tue May 20 00:00:00 EDT 2008  GALT
296    796 BUTTERCUP CIR    2159  Tue May 20 00:00:00 EDT 2008  GALT
307      1092 MAUGHAM CT    3746  Tue May 20 00:00:00 EDT 2008  GALT
372         201 CARLO CT    1080  Mon May 19 00:00:00 EDT 2008  GALT
402  746 MOOSE CREEK WAY    1100  Mon May 19 00:00:00 EDT 2008  GALT
409        332 PALIN AVE    1204  Mon May 19 00:00:00 EDT 2008  GALT
439        913 COBDEN CT    1555  Mon May 19 00:00:00 EDT 2008  GALT
454      709 CIMMARON CT    1798  Mon May 19 00:00:00 EDT 2008  GALT
480    1042 STARBROOK DR    1928  Mon May 19 00:00:00 EDT 2008  GALT
508      200 OAKWILDE ST    1606  Mon May 19 00:00:00 EDT 2008  GALT
652        925 COBDEN CT    1140  Fri May 16 00:00:00 EDT 2008  GALT
761       294 SPARROW DR    2214  Fri May 16 00:00:00 EDT 2008  GALT
800     1214 DAWNWOOD DR    1548  Fri May 16 00:00:00 EDT 2008  GALT
957     82 WILDFLOWER DR    1262  Thu May 15 00:00:00 EDT 2008  GALT
968     1178 WARMWOOD CT    1770  Thu May 15 00:00:00 EDT 2008  GALT

In [2]:
x.columns

Index(['street', 'city', 'zip', 'state', 'beds', 'baths', 'sq__ft', 'type',
       'sale_date', 'price', 'latitude', 'longitude'],
      dtype='object')

In [10]:
#top 5 residency details which lie in the budget of 60000-120000, an area more than 1450, min bedroom 3 and, min bathroom 2.
x=x.copy()
x['price']= x['price'].between(60000,120000,inclusive=True)
x['sq__ft']=x['sq__ft'] >1450
x['beds']= x['beds'] >2
x['baths']= x['baths'] >1
x

C:\Users\admin\AppData\Local\Temp\ipykernel_3924\490767827.py:2: FutureWarning: Boolean inputs to the `inclusive` argument are deprecated in favour of `both` or `neither`.
  x['price']= x['price'].between(60000,120000,inclusive=True)

,street,city,zip,state,beds,baths,sq__ft,type,sale_date,price,latitude,longitude
0,3526 HIGH ST,SACRAMENTO,95838,CA,False,False,False,Residential,Wed May 21 00:00:00 EDT 2008,False,38.631913,-121.434879
1,51 OMAHA CT,SACRAMENTO,95823,CA,False,False,False,Residential,Wed May 21 00:00:00 EDT 2008,False,38.478902,-121.431028
2,2796 BRANCH ST,SACRAMENTO,95815,CA,False,False,False,Residential,Wed May 21 00:00:00 EDT 2008,False,38.618305,-121.443839
3,2805 JANETTE WAY,SACRAMENTO,95815,CA,False,False,False,Residential,Wed May 21 00:00:00 EDT 2008,False,38.616835,-121.439146
4,6001 MCMAHON DR,SACRAMENTO,95824,CA,False,False,False,Residential,Wed May 21 00:00:00 EDT 2008,False,38.519470,-121.435768
...,...,...,...,...,...,...,...,...,...,...,...,...
980,9169 GARLINGTON CT,SACRAMENTO,95829,CA,False,False,False,Residential,Thu May 15 00:00:00 EDT 2008,False,38.457679,-121.359620
981,6932 RUSKUT WAY,SACRAMENTO,95823,CA,False,False,False,Residential,Thu May 15 00:00:00 EDT 2008,False,38.499893,-121.458890
982,7933 DAFFODIL WAY,CITRUS HEIGHTS,95610,CA,False,False,False,Residential,Thu May 15 00:00:00 EDT 2008,False,38.708824,-121.256803
983,8304 RED FOX WAY,ELK GROVE,95758,CA,False,False,False,Residential,Thu May 15 00:00:00 EDT 2008,False,38.417000,-121.397424
984,3882 YELLOWSTONE LN,EL DORADO HILLS,95762,CA,False,False,False,Residential,Thu May 15 00:00:00 EDT 2008,False,38.655245,-121.075915

In [7]:
#separate list of residential apartments with more than 2 beds with particular columns
resi= x[(x['type'] == 'Residential') & (x['beds'] > 2)]
result= resi[['city', 'baths', 'sq__ft', 'beds', 'price', 'type']]
print(result)

                city  baths  sq__ft  beds   price         type
1         SACRAMENTO      1    1167     3   68212  Residential
6         SACRAMENTO      2    1104     3   90895  Residential
7         SACRAMENTO      1    1177     3   91002  Residential
9          RIO LINDA      2    1146     3   98937  Residential
10        SACRAMENTO      2     909     3  100309  Residential
..               ...    ...     ...   ...     ...          ...
980       SACRAMENTO      3    2280     4  232425  Residential
981       SACRAMENTO      2    1477     3  234000  Residential
982   CITRUS HEIGHTS      2    1216     3  235000  Residential
983        ELK GROVE      2    1685     4  235301  Residential
984  EL DORADO HILLS      2    1362     3  235738  Residential

[715 rows x 6 columns]

In [4]:
#chepeast villa in california.
ca_villa= x[(x['state'] == 'CA') & (x['type']=='villa')]
cheapest_property= ca_villa.loc[ca_villa['price'].idxmin()]
print('the cheapest villa property in California is located at', cheapest_property['street'],',',cheapest_property['city'], ',', cheapest_property ['price'])

the cheapest villa property in California is located at 5840 WALERGA RD , SACRAMENTO , 40000

In [8]:
residential = x[(x['typ'] > 60000) & (x['price'] < 120000) & (x['sq__ft'] > 1450) & (x['beds'] >= 3) & (x['baths'] >= 2) & (x['type'] == 'residential')]

# Print the first 5 rows of the filtered DataFrame
print(residential.head(5))

Empty DataFrame
Columns: [street, city, zip, state, beds, baths, sq__ft, type, sale_date, price, latitude, longitude]
Index: []